
const characters = [
  {
    id: 'zhenya',
    name: 'Женя',
    color: '#e0e0e0',
    sprites: { neutral: 'characters/zhenya_neutral.png' },
  },
  {
    id: 'regina',
    name: 'Реджина',
    color: '#4fc3f7',
    sprites: { neutral: 'characters/regina_neutral.png' },
  },
  {
    id: 'gast',
    name: 'Гаст',
    color: '#4dd0e1',
    sprites: { neutral: 'characters/gast_neutral.png' },
  },
  {
    id: 'hel',
    name: 'Хел',
    color: '#ffd54f',
    sprites: { neutral: 'characters/hel_neutral.png' },
  },
  {
    id: 'shima',
    name: 'Шима',
    color: '#ce93d8',
    sprites: { neutral: 'characters/shima_neutral.png' },
  },
  {
    id: 'bri',
    name: 'Бри',
    color: '#ffb300',
    sprites: { neutral: 'characters/bri_neutral.png' },
  },
  {
    id: 'rey',
    name: 'Рей',
    color: '#8d6e63',
    sprites: { neutral: 'characters/rey_neutral.png' },
  },
  {
    id: 'katerina',
    name: 'Катерина',
    color: '#a1887f',
    sprites: { neutral: 'characters/katerina_neutral.png' },
  },
  {
    id: 'liliar',
    name: 'Лилиар',
    color: '#80cbc4',
    sprites: { neutral: 'characters/liliar_neutral.png' },
  },
  {
    id: 'twins',
    name: 'Близняшки',
    color: '#90caf9',
    sprites: { neutral: 'characters/twins_neutral.png' },
  },
];

const chapters = [
  {
    id: 'ch1',
    title: 'Глава 1',
    subtitle: 'Падение',
    scenes: [
      {
        id: 'ch1_scene1',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_bathroom.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [],
        dialogues: [
          { speaker: null, text: 'Мои волосы покрывали собой пол...' },
          { speaker: null, text: 'На дворе стоял поздний вечер, мать требовала, чтобы я убрала в ванной.' },
          { speaker: null, text: 'Я, слегка подавленная непрерывным звуком собственного сердцебиения, как обычно, направилась к ванной комнате.' },
          { speaker: 'Женя', text: 'Вот чёрт.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Пришлось убирать волосы, будучи в одежде, так как банные халаты мать стирала, поэтому не разрешала их носить.' },
          { speaker: null, text: 'Это была моя вина, потому что я натянула на себя очень дорогое платье, купленное матерью, и решила, что мне незачем тратить деньги на вещи, в которых можно убираться.' },
          { speaker: 'Мать', text: 'Женя, мне слышно, как ты шмыгаешь носом! Поправься уже!', characterId: 'mother', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Да, мам...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я и сама прекрасно слышала, как шмыгаю носом, и поэтому ещё больше ненавидела себя.' },
          { speaker: null, text: 'Почему я не могу просто вылечиться? Почему я беспокою семью, будучи больной?' },
          { speaker: null, text: 'Стоило ли вообще рождаться, если ты не можешь самостоятельно вытирать слёзы?' },
        ],
        choices: [
          { text: 'Ответить мать грубовато', nextSceneId: 'ch1_scene2a', effects: { trustShima: 5 } },
          { text: 'Промолчать и продолжить уборку', nextSceneId: 'ch1_scene2b' },
        ],
      },
      {
        id: 'ch1_scene2a',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_bathroom.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: 'Женя', text: 'Я тебе что, собака, чтобы ты мне приказывала?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Из комнаты послышался резкий смешок.' },
          { speaker: 'Мать', text: 'Ты хоть знаешь, что это было очень смешно?', characterId: 'mother', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Это не была мать. Мать сейчас была на работе. Вероятнее всего, это была моя младшая сестра, Эмма, которая решила прикинуться мамой.' },
          { speaker: 'Женя', text: 'Эмма! Ты чёртова мелкая...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Послышались быстрые шаги, убегающие прочь от ванной комнаты.' },
          { speaker: 'Женя', text: 'Какое же мне дело до всего этого...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch1_scene3' },
        ],
        dissociationChange: 5,
      },
      {
        id: 'ch1_scene2b',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_bathroom.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я промолчала, потому что не имела права на собственные эмоции, как и все дети, не работающие до 18 лет.' },
          { speaker: null, text: 'Продолжила убирать волосы с пола.' },
          { speaker: null, text: 'Сердце колотилось как бешеное... Как будто оно пыталось вырваться из моей груди, чтобы найти что-то, чего мне не хватало.' },
          { speaker: null, text: 'Однако, я не знала, чего мне хотелось. Нет, я и сейчас не знаю. Нет никакого способа, чтобы успокоить себя. Нет никакого способа, чтобы исправить меня, сломанную машину.' },
          { speaker: null, text: 'Что такое жизнь, если каждый день — это лишь борьба с самой собой? Интересно, когда я успокоюсь...' },
          { speaker: 'Женя', text: 'Наверное, никогда.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Сколько бы я не втирала в себя мысли о том, что я — никчёмное создание, пришедшее в этот мир лишь для того, чтобы грызть себя, она не заставит меня заплакать.' },
          { speaker: null, text: 'Потому что, если ты рыдаешь из-за того, что ненавидишь себя, это просто слабость. А я не хочу быть слабой.' },
          { speaker: null, text: 'Пусть мир думает, что я робкая. Потому что, если я скажу, что мне плевать, то обману лишь себя.' },
          { speaker: null, text: 'Я трусиха. И все должны знать. Мне нечего скрывать. Однако...' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch1_scene3' },
        ],
        dissociationChange: 10,
      },
      {
        id: 'ch1_scene3',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_room.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Погода на улице была такой же ужасной, как и моё настроение. Дождь за окном шумел как белый шум, пытаясь заткнуть мои мысли.' },
          { speaker: null, text: 'Я открыла окно. Пусть дождь зальёт мою комнату. Мне всё равно. Я ненавижу душноту, из-за которой мне трудно дышать.' },
          { speaker: 'Женя', text: 'Как прекрасно...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Дождь лил на мою руку, растекаясь по коже мурашками. Он смывал пыль и грязь с моей души.' },
          { speaker: null, text: 'Холодный. Нежный. Беспристрастный. Дождь не различает, кто перед ним. Принцесса или нищий — он одинаково смывает их слёзы.' },
          { speaker: 'Женя', text: 'Если бы всё было так же просто... Просто раствориться в воде. Исчезнуть. Не оставить следов.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Смерть пугает всех. А что, если смерть — это лишь погружение в воду? Сначала боль от нехватки воздуха, а затем...' },
          { speaker: null, text: 'Во мне столько всего... Всё это бесполезно. Словно я втиснута в тесный мешок. Но нет сил нарушить данную мне судьбу.' },
          { speaker: null, text: 'Потому что зачем мне бороться с ветряными мельницами? Если я выбью одну стену, на меня обрушатся другие.' },
          { speaker: 'Женя', text: 'Зачем всё это? Зачем я живу?', characterId: 'zhenya', position: 'center', emotion: 'neutral', effect: 'glitch' },
          { speaker: null, text: 'Нет. Не сейчас. Я не должна думать об этом. Слишком поздно, чтобы искать смысл жизни.' },
          { speaker: null, text: 'Погода была такой же ужасной, как и мое настроение. Небо покрыто тучами, а дождь стучал по окну...' },
          { speaker: null, text: 'Я закрыла окно, оставив лужу на подоконнике. Пусть она останется там как память о том, что я когда-то чувствовала что-то.' },
        ],
        choices: [
          { text: 'Пойти готовить ужин', nextSceneId: 'ch1_scene4' },
          { text: 'Остаться в комнате', nextSceneId: 'ch1_scene4b' },
        ],
        dissociationChange: 10,
      },
      {
        id: 'ch1_scene4',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_kitchen.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я пошла на кухню готовить ужин. Кастрюля с водой стояла на плите.' },
          { speaker: null, text: 'Нарезать овощи. Добавить в бульон. Следить, чтобы не убежало.' },
          { speaker: null, text: 'Механические движения. Руки помнят, что делать, даже когда голова пуста.' },
          { speaker: null, text: 'Младшая сестра Эмма сидела за столом, уставившись в свой телефон.' },
          { speaker: 'Эмма', text: 'Мама сказала, что придёт поздно. Опять.', characterId: 'emma', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Понятно.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Эмма', text: 'Ты всё ещё болеешь?', characterId: 'emma', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Да.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Короткие ответы. Всё, на что хватает сил.' },
          { speaker: null, text: 'Я помешивала суп, смотря, как клубы пара поднимаются к вытяжке. Простые моменты — вот что удерживает меня.' },
          { speaker: null, text: 'Странно, но именно в такие моменты я чувствую себя почти нормально. Когда руки заняты, а мысли — нет.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch1_scene5' },
        ],
      },
      {
        id: 'ch1_scene4b',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_room.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я осталась в комнате, лёжа на кровати и глядя в потолок.' },
          { speaker: null, text: 'Потрескавшаяся штукатурка. Следы от мухи, раздавленной много лет назад.' },
          { speaker: null, text: 'Всё такое знакомое. Всё такое... пустое.' },
          { speaker: null, text: 'Катерина написала мне сообщение: "Ты как?"' },
          { speaker: 'Женя', text: '...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я не ответила. Не потому что не хочу. Просто не знаю, что сказать.' },
          { speaker: null, text: '"Хорошо" — это ложь. "Плохо" — это жалобы. Лучше промолчать.' },
          { speaker: null, text: 'Через час мне всё же пришлось идти готовить ужин. Эмма ждала.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch1_scene5' },
        ],
        dissociationChange: 5,
      },
      {
        id: 'ch1_scene5',
        chapter: 'ch1',
        background: 'backgrounds/bg_earth_bathroom.jpg',
        music: 'bgm_earth_sad',
        rain: true,
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Вечер. После ужина я пошла в ванную. Нужно было смыть с себя день.' },
          { speaker: null, text: 'Плитка под ногами была ледяной. Вода из крана гремела, наполняя тишину.' },
          { speaker: 'Женя', text: 'Ещё один день прожит. Ещё один день побеждён.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я сняла одежду и опустилась в ванну. Горячая вода обняла моё тело, и я почувствовала, как напряжение немного отпускает.' },
          { speaker: null, text: 'Вода... Она всегда была моим убежищем. В детстве я могла часами сидеть в ванне, пока пальцы не сморщивались.' },
          { speaker: null, text: 'Мать ругала меня за это. "Вода дорогая!" — кричала она. Но сейчас она не дома.' },
          { speaker: 'Женя', text: 'Если бы можно было просто... уйти. В другой мир. В другую жизнь.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я закрыла глаза и погрузилась глубже, позволяя воде закрыть мои уши. Звуки мира стали приглушёнными, далёкими.' },
          { speaker: null, text: 'Голова кружилась от жара. Или от чего-то другого...' },
          { speaker: null, text: 'Я почувствовала странное покалывание в кончиках пальцев. Вода... светилась?' },
          { speaker: null, text: 'Нет, это невозможно. Я просто устала. Слишком много думала.' },
          { speaker: null, text: 'Но свет не исчезал. Он становился ярче, меняя цвет с прозрачного на голубой, затем на глубокий фиолетовый...' },
          { speaker: 'Женя', text: 'Ч-что...?', characterId: 'zhenya', position: 'center', emotion: 'neutral', effect: 'glitch' },
          { speaker: null, text: 'Я попыталась встать, но тело не слушалось. Вода стала горячей, невыносимо горячей...' },
          { speaker: null, text: 'Или это был холод? Я уже не могла различить. Мир кружился, растворяясь в вихре цвета и света.' },
          { speaker: null, text: 'Последнее, что я увидела — это собственное отражение в воде. Но оно было не моим.' },
          { speaker: null, text: 'Голубая кожа. Яркие глаза. И чужое, прекрасное лицо...', effect: 'glitch' },
        ],
        choices: [
          { text: '...', nextSceneId: 'ch1_scene6' },
        ],
        transition: 'glitch',
        dissociationChange: 30,
      },
      {
        id: 'ch1_scene6',
        chapter: 'ch1',
        background: 'backgrounds/bg_lalin_palace_bedroom.jpg',
        music: 'bgm_lalin_mystery',
        characters: [],
        dialogues: [
          { speaker: null, text: 'Я открыла глаза.' },
          { speaker: null, text: 'Потолок был невероятно высоким, украшенным сверкающими камнями. Свет, падающий через окна, был... неправильным. Слишком голубым, слишком мягким.' },
          { speaker: null, text: 'Я лежала на кровати, которая была больше моей комнаты на Земле. Шёлковые простыни скользили по коже — голубой коже.' },
          { speaker: '???', text: 'Простите, принцесса Реджина, но что вы здесь делаете?', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Передо мной стояли две абсолютно одинаковые девушки с длинными серебристыми волосами и лазуритовыми глазами.' },
          { speaker: 'Женя', text: 'П-принцесса? Я? Вы ошиблись...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: '???', text: 'Ой-ой. Простите, что мешаем вам отдыхать, ваша высочество. Но вы так давно не показывались, мы решили проведать вас.', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Моя голова раскалывалась. Принцесса? Высочество? Что здесь происходит?' },
          { speaker: null, text: 'Я посмотрела на свои руки. Голубые. Совершенно голубые, словно выкрашенные акварелью.' },
          { speaker: null, text: 'Нет, не выкрашенные. Это была моя кожа. Настоящая, естественная.' },
          { speaker: 'Женя', text: 'Это... сон?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: '???', text: 'Простите, но вы ненормально себя чувствуете? Мы можем позвать целителя.', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Я попыталась встать, но голова закружилась, и я упала обратно на кровать.' },
          { speaker: null, text: 'Где я? Что это за место? И почему все называют меня принцессой?' },
          { speaker: null, text: 'Сквозь окно я увидела... другой мир. Голубые деревья. Сверкающие цветы. Небо, окрашенное в оттенки сирени и бирюзы.' },
          { speaker: null, text: 'Это был не Земля. Это был совершенно другой мир.' },
        ],
        choices: [
          { text: 'Спросить, где вы находитесь', nextSceneId: 'ch2_scene1' },
        ],
        transition: 'fade',
      },
    ],
  },
  {
    id: 'ch2',
    title: 'Глава 2',
    subtitle: 'Пробуждение',
    scenes: [
      {
        id: 'ch2_scene1',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_palace_bedroom.jpg',
        music: 'bgm_lalin_mystery',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'twins', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: 'Женя', text: 'Где... я?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Близняшки', text: 'В ваших покоях, ваша высочество. В Имперском дворце Ла Лин.', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Ла Лин. Имперский дворец. Слова звучали как из сказки, но всё вокруг было слишком реальным.' },
          { speaker: null, text: 'Сверкающие камни на стенах. Нежный аромат незнакомых цветов. Воздух, который щекотал лёгкие, наполняя их странной энергией.' },
          { speaker: 'Женя', text: 'Ла Лин...?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Близняшки', text: 'Вам действительно нужен целитель. Мы сейчас позовём госпожу Лилиар.', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Одна из близняшек поспешила к двери, а другая осталась со мной, изучая моё лицо с тревогой.' },
          { speaker: null, text: 'Я посмотрела на своё отражение в зеркале напротив. Долгие голубые волосы с розовыми прядями. Большие глаза цвета неонового голубого. Изящные черты лица.' },
          { speaker: null, text: 'Красивое лицо. Незнакомое лицо. Чужое лицо.' },
          { speaker: 'Женя', text: 'Кто... я?', characterId: 'zhenya', position: 'center', emotion: 'neutral', effect: 'glitch' },
          { speaker: null, text: 'Отражение не ответило. Но в его глазах мелькнуло что-то — смех или страх?' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch2_scene2' },
        ],
      },
      {
        id: 'ch2_scene2',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_palace_bedroom.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'liliar', position: 'left', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'В покои вошла девушка с длинными тёмными волосами и очень бледной серой кожей.' },
          { speaker: '???', text: 'Ваша высочество, вы очнулись. Как вы себя чувствуете?', characterId: 'liliar', position: 'left', emotion: 'neutral' },
          { speaker: null, text: 'Её голос был мягким, успокаивающим. Непроизвольно мне захотелось довериться ей.' },
          { speaker: 'Женя', text: 'Голова... кружится. Что со мной?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: '???', text: 'Ваша душа пережила большой стресс. Вы потеряли память после... инцидента. Я — Коу Лилиар, ваш личный целитель.', characterId: 'liliar', position: 'left', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Память? Нет, я помню всё. Я...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я замолчала. Что я помню? Мрачную комнату. Дождь. Ванну...' },
          { speaker: null, text: 'Но это было в другой жизни. В другом мире. В мире, который не мог существовать.' },
          { speaker: 'Лилиар', text: 'Не торопитесь. Воспоминания вернутся постепенно. Сейчас вам нужно отдохнуть.', characterId: 'liliar', position: 'left', emotion: 'neutral' },
          { speaker: null, text: 'Она положила прохладную руку мне на лоб, и я почувствовала, как что-то тёплое разливается внутри меня. Боль в голове утихла.' },
          { speaker: 'Лилиар', text: 'Лучше?', characterId: 'liliar', position: 'left', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Да... Спасибо.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Лилиар', text: 'Если вам что-нибудь понадобится — позовите. Близняшки будут рядом.', characterId: 'liliar', position: 'left', emotion: 'neutral' },
          { speaker: null, text: 'Она улыбнулась и вышла, оставив меня наедине с сумасшедшими мыслями.' },
          { speaker: null, text: 'Ла Лин. Принцесса. Целитель. Близняшки. Всё это было слишком нереальным, чтобы быть правдой.' },
          { speaker: null, text: 'Но если это был сон, то почему он такой... яркий? Почему я чувствовала холод плитки под ногами?' },
          { speaker: 'Женя', text: 'Если это сон... пусть он длится вечно.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        choices: [
          { text: 'Встать и осмотреть комнату', nextSceneId: 'ch2_scene3' },
          { text: 'Попытаться снова уснуть', nextSceneId: 'ch2_scene3b' },
        ],
      },
      {
        id: 'ch2_scene3',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_palace_garden.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'shima', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я встала и надела лёгкое платье, оставленное у кровати. Ткань была невероятно мягкой, словно соткана из облаков.' },
          { speaker: null, text: 'Выйдя из покоев, я попала в дворцовый сад. Моё дыхание перехватило.' },
          { speaker: null, text: 'Голубые деревья. Сверкающие цветы, которые переливались всеми оттенками фиолетового. Фонтан, из которого струилась светящаяся вода.' },
          { speaker: null, text: 'Воздух пах магией — сладко, слабо, завораживающе.' },
          { speaker: '???', text: 'Ну-ну. Кто это у нас тут блуждает без присмотра?', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Я обернулась. Ко мне приближалась девушка с лавандовыми волосами в изысканных кудрях. Её платье было настолько пышным, что оно казалось живым существом.' },
          { speaker: null, text: 'На голове — тиара с голубыми кристаллами. Глаза — фиолетовые, холодные, оценивающие.' },
          { speaker: '???', text: 'О, это всего лишь ты, сестрица. Я думала, ты всё ещё лежишь в обмороке, как истинная драма-квин.', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Сестрица? Ты моя сестра?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: '???', text: 'Ха! Она ещё и притворяется, что забыла меня. Как мило.', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Она сделала шаг ближе, и я заметила, что её улыбка не доходит до глаз.' },
          { speaker: 'Шима', text: 'Послушай, Реджина. Я не знаю, какую игру ты задумала, но знай — я не верю ни единому твоему слову.', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: 'Шима', text: 'Потеря памяти? Слишком удобно. Ты просто хочешь, чтобы все сочувствовали бедной маленькой принцессе.', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Я... я не притворяюсь.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Шима', text: 'Конечно, конечно. А теперь, если позволишь, меня ждут дела поважнее, чем разговоры с лже-амнезийной.', characterId: 'shima', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Она развернулась и ушла, оставив за собой шлейф парфюма и неприязни.' },
          { speaker: null, text: 'Шима. Моя сестра. Враждебная, красивая, трагичная.' },
          { speaker: null, text: 'Что же произошло между нами в этом мире?' },
        ],
        choices: [
          { text: 'Продолжить прогулку по саду', nextSceneId: 'ch2_scene4' },
        ],
        dissociationChange: -5,
      },
      {
        id: 'ch2_scene3b',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_palace_bedroom.jpg',
        music: 'bgm_lalin_mystery',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я легла обратно и закрыла глаза, надеясь, что проснусь в своей серой комнате на Земле.' },
          { speaker: null, text: 'Но когда открыла глаза — всё было тем же. Голубые стены. Сверкающие камни. Чужой мир.' },
          { speaker: null, text: 'Я пролежала так несколько часов, пока близняшки не пришли проведать меня.' },
          { speaker: 'Близняшки', text: 'Ваша высочество, император требует вашего присутствия на обеде.', characterId: 'twins', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Император? Мой отец?' },
          { speaker: 'Женя', text: 'Хорошо. Я готова.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Мне пришлось встать и научиться ходить заново — в этом теле всё было иначе. Легче. Как будто я весила столько же, сколько облако.' },
          { speaker: null, text: 'Близняшки помогли мне одеться в пышное голубое платье и уложить волосы.' },
          { speaker: null, text: 'Когда я увидела себя в зеркале... Я выглядела как настоящая принцесса.' },
          { speaker: null, text: 'Это было пугающе. И немного... прекрасно?' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch2_scene4' },
        ],
        dissociationChange: -10,
      },
      {
        id: 'ch2_scene4',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_river.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Я вышла из дворца к реке. Это было единственное место, куда меня не следовали.' },
          { speaker: null, text: 'Вода сверкала, отражая голубое небо. Я сняла туфли и опустила ноги в воду. Тёплая. Живая.' },
          { speaker: 'Женя', text: 'Какая красота...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'На Земле я никогда не видела такого. Реки были грязными, серыми. А эта...' },
          { speaker: null, text: 'Эта река светилась изнутри, словно в ней плавали тысячи светлячков.' },
          { speaker: null, text: 'Я закрыла глаза и позволила солнцу согреть моё лицо. Впервые за долгое время я почувствовала... покой?' },
          { speaker: null, text: 'Не полное счастье, нет. Но его призрак. Мимолётное ощущение, что мир не так ужасен.' },
          { speaker: '???', text: 'Простите, вы — принцесса Реджина?', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Я обернулась. За мной стоял молодой человек с ярко-красными волосами и бледно-голубой кожей. Его рыжие глаза изучали меня с осторожностью.' },
          { speaker: null, text: 'Шрам пересекал его левую бровь, придавая лицу суровое выражение.' },
          { speaker: '???', text: 'Меня прислали убедиться, что с вами всё в порядке после... вашего недомогания.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'А ты кто?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: '???', text: 'Гаст Лэнгдон, слуга Императора. Я также работаю на вашу сестру.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Гаст. Слуга Императора. Но его голос звучал слишком свободно для слуги.' },
          { speaker: null, text: 'Он подошёл ближе, и я заметила, что его руки покрыты шрамами. Старыми, побледневшими.' },
          { speaker: 'Гаст', text: 'Вы выглядите иначе, чем раньше. Более... мягкой.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Я... потеряла память. Многое не помню.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Понятно. Тогда позвольте мне представиться заново. Я — ваш покорный слуга.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он склонил голову, но его взгляд остался проницательным. Этот человек не верил мне.' },
          { speaker: null, text: 'Или, может быть, он не верил никому. Такие глаза появляются только у тех, кто многое повидал.' },
          { speaker: null, text: 'Далеко за рекой раздался грозный рёв. Земля содрогнулась.' },
          { speaker: 'Гаст', text: 'Монстр! Защищайте принцессу!', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Из кустов выскочило огромное чёрное существо с множеством глаз. Оно рванулось прямо на меня.' },
          { speaker: 'Женя', text: 'А-а-а!', characterId: 'zhenya', position: 'center', emotion: 'neutral', effect: 'shake' },
          { speaker: null, text: 'Я застыла от страха, не в силах пошевелиться. Существо приближалось, его глаза горели жёлтым огнём...' },
          { speaker: null, text: 'И в этот момент Гаст вихрем пронёсся мимо, выхватывая меч из-за спины.' },
          { speaker: null, text: 'Слепящая вспышка света. Рёв. Запах горелой плоти.' },
          { speaker: null, text: 'Когда я открыла глаза, существо лежало на земле, а Гаст стоял над ним, тяжело дыша. Меч в его руке светился голубым.' },
          { speaker: 'Гаст', text: 'С вашей высочествой всё в порядке?', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его рука дрожала, но голос оставался ровным. Он был ранен — тёмное пятно расходилось по его рукаву.' },
          { speaker: 'Женя', text: 'Ты ранен...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Пустяки. Главное, что вы целы.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он убрал меч в ножны и сделал шаг ко мне, протягивая руку.' },
          { speaker: 'Гаст', text: 'Пойдёмте. Я отведу вас во дворец. Здесь небезопасно.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Я взяла его руку. Она была тёплой, с мозолями от меча.' },
          { speaker: null, text: 'В этот момент, держа его руку, я впервые подумала: может, этот мир не так ужасен.' },
        ],
        choices: [
          { text: 'Поблагодарить Гаста', nextSceneId: 'ch2_scene5', effects: { trustGast: 10 } },
          { text: 'Промолчать', nextSceneId: 'ch2_scene5' },
        ],
        dissociationChange: -10,
      },
      {
        id: 'ch2_scene5',
        chapter: 'ch2',
        background: 'backgrounds/bg_lalin_palace_garden.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'gast', position: 'right', emotion: 'neutral' },
          { id: 'zhenya', position: 'left', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Гаст проводил меня обратно ко дворцу. Мы шли молча, но тишина была не тяжёлой — она была... удобной.' },
          { speaker: 'Гаст', text: 'Ваша высочество, могу я задать вам вопрос?', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Конечно.', characterId: 'zhenya', position: 'left', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Потеря памяти... Это правда? Или вы просто не хотите вспоминать?', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его вопрос был прямым, почти грубым. Но в его глазах я увидела не подозрение, а... понимание?' },
          { speaker: 'Женя', text: 'Я не знаю. Всё, что я помню... это как будто я была другим человеком. В другом месте. В другом мире.', characterId: 'zhenya', position: 'left', emotion: 'neutral' },
          { speaker: null, text: 'Это было максимально близко к правде, которую я могла сказать.' },
          { speaker: 'Гаст', text: 'Другой мир...', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он замолчал на минуту, глядя на закатное небо.' },
          { speaker: 'Гаст', text: 'Я тоже иногда думаю о другом мире. О месте, где не нужно притворяться.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его голос стал тихим, почти шёпотом. Словно он говорил не мне, а самому себе.' },
          { speaker: 'Гаст', text: 'Но мы здесь. И мы должны играть свои роли. Вы — принцесса. Я — слуга.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он остановился и повернулся ко мне. Его рыжие глаза светились в лучах заката.' },
          { speaker: 'Гаст', text: 'Но если вам когда-нибудь понадобится помощь... обращайтесь. Не к Шиме. Не к Императору. Ко мне.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Я кивнула, не зная, что ответить. Его слова звучали как обещание и как предупреждение одновременно.' },
          { speaker: null, text: 'У ворот дворца он отпустил мою руку и отступил на шаг, снова становясь безликим слугой.' },
          { speaker: 'Гаст', text: 'Доброй ночи, ваша высочество.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'И он исчез в сумерках, оставив меня с болью, которая была похожа на тоску по дому, которого у меня никогда не было.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch3_scene1' },
        ],
      },
    ],
  },
  {
    id: 'ch3',
    title: 'Глава 3',
    subtitle: 'Тени прошлого',
    scenes: [
      {
        id: 'ch3_scene1',
        chapter: 'ch3',
        background: 'backgrounds/bg_lalin_palace_garden.jpg',
        music: 'bgm_lalin_mystery',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Ночью я не могла уснуть. Слишком много мыслей. Слишком много вопросов.' },
          { speaker: null, text: 'Я вышла на балкон, глядя на луну. Она была другой — больше, сиреневой, с кольцом вокруг.' },
          { speaker: 'Женя', text: 'Какой же это мир...?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Сердце стучало в груди. Я чувствовала, как что-то накапливается внутри — страх, тоска, беспокойство.' },
          { speaker: null, text: 'Я схватилась за перила, пытаясь успокоить дыхание. Но воздух не заходил в лёгкие.' },
          { speaker: null, text: 'Голова кружилась. Мир расплывался. Я начала падать...' },
          { speaker: '???', text: 'Ваша высочество!', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Кто-то поймал меня. Сильные руки, знакомый запах — дым и ледяная мята.' },
          { speaker: 'Гаст', text: 'Дышите. Медленно. Раз. Два. Три.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его голос был тихим, твёрдым. Я попыталась подчиниться, выдыхая и вдыхая в такт его счёту.' },
          { speaker: 'Гаст', text: 'У вас паническая атака. Слушайте мой голос. Вы в безопасности.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Минуту спустя мир перестал кружиться. Я открыла глаза и увидела его лицо в нескольких сантиметрах от своего.' },
          { speaker: 'Гаст', text: 'Лучше?', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Да... Простите.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Не извиняйтесь. Вы пережили многое. Тело помнит, даже если разум забывает.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он помог мне сесть на скамейку и отступил на шаг, давая пространство.' },
          { speaker: 'Гаст', text: 'Я буду рядом, если понадоблюсь.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'И он действительно остался — стоя в тени колонны, невидимый, но присутствующий.' },
          { speaker: null, text: 'Я закрыла глаза и позволила себе почувствовать... защищённость?' },
          { speaker: null, text: 'Впервые за очень долгое время.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch3_scene2' },
        ],
        dissociationChange: -15,
      },
      {
        id: 'ch3_scene2',
        chapter: 'ch3',
        background: 'backgrounds/bg_lalin_training.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'rey', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'На следующее утро мне сказали, что мне нужно тренироваться.' },
          { speaker: null, text: '"Принцесса должна уметь защитить себя", — заявила Шима на завтраке.' },
          { speaker: null, text: 'Я оказалась на тренировочном поле. Солнечный свет, тёплая трава под ногами. Всё было таким... живым.' },
          { speaker: '???', text: 'Так-так. Реджина в платье с мечом. Зрение не из приятных.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Молодой человек с коричневыми волосами и красными кончиками оценивающе смотрел на меня. Его янтарные глаза насмешливо сверкали.' },
          { speaker: '???', text: 'Я — Рей Ак-Сан-Доулэ, инструктор по мечу. Буду учить вас основам, пока вы не пораните себя.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Ак-Сан-Доулэ? Как Хел?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Рей', text: 'О, вы помните моего младшего брата? Как мило. Не волнуйтесь — мы совершенно разные. Он — золотой мальчик, я — чёрная овца.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он подбросил мне деревянный меч. Он оказался тяжелее, чем я ожидала.' },
          { speaker: 'Рей', text: 'Ноги на ширине плеч. Руки крепче. Это меч, не букет цветов.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Тренировка была изнурительной. Рей не щадил меня, поправляя каждое движение с саркастическими замечаниями.' },
          { speaker: 'Рей', text: 'Ха! Вы машете мечом как метлой. Нет, даже хуже — как веером на балу.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Но под насмешками скрывалась забота. Когда я споткнулась, он подхватил меня, прежде чем я упала.' },
          { speaker: 'Рей', text: 'Будьте внимательнее, ваша высочество. Земля не умеет ловить.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'К концу тренировки я была вся в поту, но чувствовала странное удовлетворение. Тело горело, но ум был ясен.' },
          { speaker: 'Рей', text: 'Неплохо... для принцессы. Завтра в то же время.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он развернулся и ушёл, оставив меня с мечом в руке и незнакомым чувством силы в груди.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch3_scene3' },
        ],
        dissociationChange: -10,
      },
      {
        id: 'ch3_scene3',
        chapter: 'ch3',
        background: 'backgrounds/bg_bar.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'gast', position: 'left', emotion: 'neutral' },
          { id: 'rey', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Вечером Гаст отвёл меня в таверну "Рассвет".' },
          { speaker: null, text: 'Внутри пахло жареным мясом, пивом и табаком. Громкая музыка, смех, стук кружек.' },
          { speaker: 'Гаст', text: 'Здесь можно расслабиться. Никто не будет кланяться принцессе.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: null, text: 'Мы сели за столик в углу. Рей присоединился к нам, не спросив разрешения.' },
          { speaker: 'Рей', text: 'Расскажи, Реджина, что помнишь?', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Почти ничего. Только... мелькания. Обрывки.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Не давите на неё. Она ещё не готова.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: 'Рей', text: 'О, защитник нашёлся. Я просто спросил.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Между ними повисло напряжение. Я почувствовала, что недостаёт части истории.' },
          { speaker: 'Женя', text: 'Вы двое... друзья?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Коллеги.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: 'Рей', text: 'Бывшие напарники. До определённого инцидента.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Они переглянулись, и в их взглядах мелькнуло что-то — воспоминание о боли или предательстве?' },
          { speaker: 'Гаст', text: 'Рей...', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: 'Рей', text: 'Ладно, ладно. Не будем грузить принцессу нашим грузом.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он отпил из кружки, и я заметила, что его руки тоже покрыты шрамами. Не так сильно, как у Гаста, но достаточно.' },
          { speaker: 'Женя', text: 'Вы оба были солдатами?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Наёмниками. До того, как попали сюда.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: null, text: '"Попали сюда" — странная формулировка. Словно они не принадлежали этому миру.' },
          { speaker: 'Рей', text: 'Эй, бармен! Ещё по одной!', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Вечер прошёл в разговорах, смехе и песнях. Впервые я почувствовала себя... нормально?' },
          { speaker: null, text: 'Не как принцесса. Не как чужак. Просто как человек среди других людей.' },
        ],
        choices: [
          { text: 'Вернуться во дворец', nextSceneId: 'ch3_scene4' },
          { text: 'Остаться подольше', nextSceneId: 'ch3_scene4b', effects: { trustGast: 5 } },
        ],
      },
      {
        id: 'ch3_scene4',
        chapter: 'ch3',
        background: 'backgrounds/bg_lalin_palace_garden.jpg',
        music: 'bgm_earth_sad',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'gast', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Ночь. Мы возвращались ко дворцу по тёмной дороге.' },
          { speaker: null, text: 'Вдали виднелись огни города. Ла Лин никогда не спал — слишком много магии, слишком много жизни.' },
          { speaker: 'Гаст', text: 'Ваша высочество, я... хочу вам кое-что сказать.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его голос был серьёзным. Он остановился, глядя мне в глаза.' },
          { speaker: 'Гаст', text: 'Я не знаю, что случилось с вами. Но я вижу, как вы страдаете. И я... не хочу, чтобы вы страдали.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Моё сердце сжалось. Его слова были слишком честными, слишком открытыми.' },
          { speaker: 'Женя', text: 'Гаст...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Простите. Я переступил границы. Забудьте.', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Он отвернулся, но я остановила его, положив руку на его плечо.' },
          { speaker: null, text: 'Его плечи были напряжены, как у человека, который слишком долго нёс тяжесть.' },
          { speaker: null, text: 'Далеко за рекой вспыхнул огонь. Пламя поднялось к небу, окрашивая облака в зловещий оранжевый.' },
          { speaker: 'Женя', text: 'Что это?', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Пожар! В доме графа!', characterId: 'gast', position: 'right', emotion: 'neutral', effect: 'shake' },
          { speaker: null, text: 'Он бросился бежать, и я побежала за ним, не думая о последствиях.' },
          { speaker: null, text: 'Мы прибежали к горящему дому. Люди кричали, метались. Из окон вылезали языки пламени.' },
          { speaker: 'Гаст', text: 'Лилиар! Она была там!', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Не раздумывая, Гаст рванулся в горящее здание.' },
          { speaker: 'Женя', text: 'Гаст! Нет!', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я ждала, сердце сжимаясь от страха, пока он не вышел, неся Лилиар на руках. Она кашляла, но была жива.' },
          { speaker: 'Гаст', text: 'Всё хорошо... Всё хорошо...', characterId: 'gast', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Его лицо было закопчено, волосы обгорели. Но Лилиар была цела.' },
          { speaker: null, text: 'Я посмотрела на него — на этого человека, который снова и снова бросался в опасность ради других.' },
          { speaker: null, text: 'И подумала: может, в этом мире есть люди, ради которых стоит жить.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch3_scene5' },
        ],
        dissociationChange: -15,
      },
      {
        id: 'ch3_scene4b',
        chapter: 'ch3',
        background: 'backgrounds/bg_bar.jpg',
        music: 'bgm_lalin_warm',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
          { id: 'gast', position: 'left', emotion: 'neutral' },
          { id: 'rey', position: 'right', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Мы остались в таверне до поздна. Рей рассказывал истории о своих приключениях, и я не могла не смеяться.' },
          { speaker: 'Рей', text: 'И тут этот дракон — огромный, как дом! — открывает пасть, а я стою с одним только ножом...', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: 'Гаст', text: 'Преувеличиваешь. Это был не дракон, а перевозбуждённая ящерица.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: 'Рей', text: 'Ты просто завидуешь моей храбрости.', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Гаст покачал головой, но уголок его губ дрогнул. Он улыбался.' },
          { speaker: null, text: 'Впервые я увидела его улыбающимся. Это преобразило его лицо — шрам стал менее заметным, глаза потеплели.' },
          { speaker: 'Женя', text: 'Тебе идёт улыбка.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Гаст замер, удивлённый. Затем отвёл взгляд, слегка покраснев.' },
          { speaker: 'Гаст', text: 'Не говорите так... Я не привык.', characterId: 'gast', position: 'left', emotion: 'neutral' },
          { speaker: 'Рей', text: 'Оооо, принцесса умеет флиртовать! Кто бы мог подумать!', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: 'Женя', text: 'Это был не флирт! Я просто...', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: 'Рей', text: 'Да-да, конечно. Все мы знаем, что это "просто".', characterId: 'rey', position: 'right', emotion: 'neutral' },
          { speaker: null, text: 'Вечер закончился хорошо. Но когда мы вышли из таверны, далеко за рекой вспыхнул огонь.' },
          { speaker: null, text: 'Пожар. В доме графа. И Гаст снова бросился спасать людей.' },
          { speaker: null, text: 'Я помогала эвакуировать пострадавших. Лилиар была в порядке благодаря Гасту.' },
          { speaker: null, text: 'Этот мир требует слишком многого. Но, может, я могу дать ему кое-что взамен.' },
        ],
        choices: [
          { text: 'Продолжить', nextSceneId: 'ch3_scene5' },
        ],
        dissociationChange: -15,
      },
      {
        id: 'ch3_scene5',
        chapter: 'ch3',
        background: 'backgrounds/bg_lalin_palace_bedroom.jpg',
        music: 'bgm_lalin_mystery',
        characters: [
          { id: 'zhenya', position: 'center', emotion: 'neutral' },
        ],
        dialogues: [
          { speaker: null, text: 'Ночь. Я лежала в кровати, не в силах уснуть.' },
          { speaker: null, text: 'Слишком много всего произошло за один день. Монстр. Тренировка. Таверна. Пожар.' },
          { speaker: null, text: 'И Гаст. Всегда Гаст — рядом, спасающий, защищающий.' },
          { speaker: 'Женя', text: 'Кем бы он ни был раньше... сейчас он мой единственный союзник.', characterId: 'zhenya', position: 'center', emotion: 'neutral' },
          { speaker: null, text: 'Я закрыла глаза, пытаясь вспомнить своё прошлое. Мрачную комнату. Дождь. Ванну...' },
          { speaker: null, text: 'Был ли тот мир реальностью? Или это всего лишь странный сон, навеянный болезнью?' },
          { speaker: null, text: 'Я не знала. Но когда я думала о Гасте, о Рее, о Лилиар... мне становилось легче.' },
          { speaker: null, text: 'Может, дом — это не место. Может, дом — это люди.' },
          { speaker: null, text: 'И если так... то я, может быть, нашла свой дом в этом странном, прекрасном мире.' },
          { speaker: null, text: 'Луна светила в окно, окрашивая комнату в серебристо-голубой. Далёкий звук колоколов.' },
          { speaker: null, text: 'Я заснула с мыслью о том, что завтра будет новый день. И я буду готова.' },
          { speaker: null, text: 'Но глубоко внутри я знала — что-то грядёт. Что-то, что изменит всё.' },
          { speaker: null, text: 'И я не была готова. Никто не был.' },
        ],
        choices: [
          { text: 'Завершить демо-версию', nextSceneId: 'ending_demo' },
        ],
      },
      {
        id: 'ending_demo',
        chapter: 'ch3',
        background: 'backgrounds/bg_title.jpg',
        music: 'bgm_lalin_mystery',
        characters: [],
        dialogues: [
          { speaker: null, text: '*** Демо-версия завершена ***' },
          { speaker: null, text: 'Спасибо за игру в "Тени мрачного бытия"!' },
          { speaker: null, text: 'Это была демо-версия, включающая первые три главы новеллы.' },
          { speaker: null, text: 'Полная версия будет включать 5 глав с множественными концовками.' },
          { speaker: null, text: 'Ваш выбор имеет значение. Ваши действия формируют судьбу Жени.' },
          { speaker: null, text: 'Сохраните игру, чтобы продолжить позже.' },
          { speaker: null, text: '*** Конец демо-версии ***' },
        ],
        choices: [],
      },
    ],
  },
];

// Helper function to find a scene by ID
function findScene(sceneId) {
  for (const chapter of chapters) {
    const scene = chapter.scenes.find((s) => s.id === sceneId);
    if (scene) return { chapter, scene };
  }
  return null;
}

// Helper function to find a character by ID
function findCharacter(characterId) {
  return characters.find((c) => c.id === characterId);
}


window.characters = characters;
window.chapters = chapters;
